Put links back on one line
caldav/duc_to_md pull request #1
Opened 2016-12-05 14:56 UTC by nottrobin

2016-12-05 15:20 UTC, pmahnke requested changes
looks like you might need to run that script twice?

2016-12-05 15:20 UTC, pmahnke commented on data/en_.md
>  ![Bring your content to the frontpage](https://developer.ubuntu.com/static/dev
this doesn't look right, do you need to run it a second time @nottrobin

2016-12-05 15:20 UTC, pmahnke commented on data/en_blog_2015_.md
> +372-464d-b279-ee92a2e5ce53-media/2015/11/12/paho_logo_400.png)The [EclipseFoundation](http://eclipse.org) has become a new home for a number of IoT
another

2016-12-05 15:20 UTC, pmahnke commented on data/en_blog_2015_.md
> +TnsnMWCUeORzrE6M5nJHG7iJ1ChHz0kGK2bDaVIaHczp0kELbNsiRrDxiROPU6A_dbiocCn6dZQdbO-RyWsXDAWS7iNbRD_vvit2tI)
another

2016-12-05 15:26 UTC, nottrobin commented
@pmahnke fixed, I hope?

2016-12-05 15:29 UTC, pmahnke approved these changes
LGTM 👍

2017-03-08 03:01 UTC, nottrobin commented
I think this is redundant as the code now live in [ubuntudesign/phone-docs](https://github.com/ubuntudesign/phone-docs). Closing.

2017-03-08 03:01 UTC, closed without merging